
source 'https://rubygems.org'
gem 'atomic', '1.1.12'
gem 'rails', '4.0.0'
gem 'mysql2'

gem 'uglifier', '>= 1.3.0'
#gem 'coffee-rails', '~> 4.0.0'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

gem 'cancan'
gem 'haml'
gem 'sass'
gem 'sass-rails', '~> 4.0.0'

gem 'activeadmin',         github: 'gregbell/active_admin', branch: 'rails4'
gem 'ransack',             github: 'ernie/ransack',         branch: 'rails-4'
#gem 'inherited_resources', github: 'josevalim/inherited_resources'
gem 'formtastic',          github: 'justinfrench/formtastic'

gem 'rmagick', '2.13.2'
gem 'carrierwave'
#gem 'galetahub-simple_captcha', :require => 'simple_captcha', :git => 'git://github.com/galetahub/simple-captcha.git'
#gem 'simple_captcha', :git => 'git://github.com/galetahub/simple-captcha.git'
gem 'kaminari'

gem 'russian', :git => 'git://github.com/yaroslav/russian.git'
#gem 'acts_as_commentable_with_threading', :git=> 'git://github.com/dfischer/acts_as_commentable_with_threading.git'

gem 'devise'

gem 'whenever'
gem 'delayed_job_active_record'
#gem 'ts-delayed-delta',  :require => 'thinking_sphinx/deltas/delayed_delta'
gem 'thinking-sphinx', '2.0.14'

gem 'jquery-rails'
gem 'tinymce-rails', github: 'spohlenz/tinymce-rails', branch: 'tinymce-4'
gem 'tinymce-rails-langs'
gem 'tinymce_spellcheck'

gem "remotipart", "~> 1.0" # ajax uploading files

gem 'paper_trail',  github: 'airblade/paper_trail', branch: 'rails4'

gem 'spreadsheet'

gem "geocoder"

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
#gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'execjs'
gem 'therubyracer'

group :development, :test do
  gem 'ruby_parser'
  gem 'capistrano'
  gem 'capistrano-ext'
  gem 'capistrano-deploy'
  gem 'rvm-capistrano'
  gem 'quiet_assets'
  gem 'thin'

  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-spork'
  gem 'guard-rspec'
  gem 'guard-livereload'

  gem 'rspec-rails'
  gem 'spork-rails', github: 'sporkrb/spork-rails'
  gem 'rb-inotify', require: false
  gem 'email_spec'
  gem 'database_cleaner'
  gem 'rack-livereload'
  gem 'factory_girl_rails'
  gem 'awesome_print'
  gem 'dotenv-rails'
  gem 'pry-rails'
end

